# Numpy

In [4]:
# It is a fundamental pacakage that provides efficient storage and operation for multidimensional arrays. At first we import this 
# pacakge using alias
import numpy as np

In [2]:
# to create a numpy array from a python list or tuple,use np.array()
list1=[[1,2,4],[4,5,6]]
list1

[[1, 2, 4], [4, 5, 6]]

In [3]:
a1=np.array(list1)

In [4]:
a1

array([[1, 2, 4],
       [4, 5, 6]])

In [5]:
type(a1)

numpy.ndarray

# numpy array attributes:

In [7]:

#dtype:we can check the  type of the elements of an array with dtype
a1.dtype

dtype('int64')

In [9]:
a2=[[2.2,3.4],[4,5]]
a3=np.array(a2)

In [13]:
a3.dtype# observe that dtype of an array having homogeneity in array elements, same dtype, we can also set it.
a4=np.array(list1,dtype='float32')
a4.dtype

dtype('float32')

In [14]:
# we can recast the datatype by astype() method
a5=a3.astype(int)
a5

array([[2, 3],
       [4, 5]])

In [15]:
# size: return the number of elements of an array
a3.size

4

In [16]:
#ndim: returns the number of dimension
a4.ndim

2

In [17]:
#shape: number of element of each dimension
a3.shape

(2, 2)

In [18]:
#note there is a diiference between 1d array and 2d array with one row or column
a6=np.arange(6)

In [19]:
a6

array([0, 1, 2, 3, 4, 5])

In [20]:
a6.shape

(6,)

In [32]:
a7=np.array([[0,1,2,3,4,5]])
a7.shape

(1, 6)

In [31]:
a7.T.shape


(6, 1)

In [33]:
a7.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# numpy built in function for array creation 


#zeros():create an array of given shapes filled with zeros
a=np.zeros(5)
a

In [36]:
b=np.zeros((3,4),dtype='int_')
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
#ones():create an array of given shapes filled with ones
c=np.ones((2,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
#full():creates an array of given shape with value
a=np.full((3,4),3.4)
a

array([[3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4]])

In [41]:
#eye():create an identity array
d=np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
#arange(start,stop,step): creates evenly spaced values.
x=np.arange(2,20,3)

In [43]:
x

array([ 2,  5,  8, 11, 14, 17])

In [44]:
#random.normal(loc,scale,size) :creates a array of shape size with elements bein g independent realization of a normal variable
# mean loc and standard deviation scale
y= np.random.normal(0,1,size=(3,3))

In [45]:
y

array([[ 1.02875264e-04, -1.95812496e+00, -1.16331079e-01],
       [-7.66072566e-01, -9.48950949e-02,  1.12783351e+00],
       [ 9.49125142e-01, -3.50479523e-01,  3.73852421e-01]])

# array indexing

In [47]:
# in indexing arrays , it is important if we index a multidimensional array with fewer than dimension it returns a sub-array.
a

array([[3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4]])

In [48]:
a[1]

array([3.4, 3.4, 3.4, 3.4])

In [49]:
a[1][2]

np.float64(3.4)

In [50]:
# we already seen this type of indexing .numpy suuports multidimensional indexing
a[1,0]

np.float64(3.4)

In [51]:
# we can slicing the array as we ahve previously seen for list or tuples.
a[:2,1:]

array([[3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4]])

In [53]:
# one main difference between numpy slicing and list slicing is that array slicing provides a view of original list where as
# list slicing copies the list. If a subarray comes from slicing and modified it , it also modified the original array but
#in list slicing this not happens as we seen it earlier
e=a[:-3:-1,::2]
e

array([[3.4, 3.4],
       [3.4, 3.4]])

In [55]:
e[0,1]=5
a#the change  appears a too

array([[3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 5. , 3.4]])

In [56]:
# to change this default behaviour , we use: copy() and array() constructor method
e=a[:-3:-1,::2].copy()
e

array([[3.4, 5. ],
       [3.4, 3.4]])

In [57]:
e[1,1]=6
a# the change does not appear not in a 

array([[3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 5. , 3.4]])

In [61]:
e=np.array(a[:-3:-1,::2])
e[1,1]=7

a# the change does not appear not in a

array([[3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 5. , 3.4]])

In [1]:
#indexing array with other array
f=[i for i in range(1,29,2)]

In [5]:
g=np.array(f)

In [13]:
c=np.arange(10,5,-1)

In [14]:
print('g='+str(g)+'\n'+'c='+str(c)+'\n'+'g[c]='+str(g[c]))

g=[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27]
c=[10  9  8  7  6]
g[c]=[21 19 17 15 13]


In [15]:
#index must be integers 

# Reshaping arrays

In [16]:
#one major difference between numpy array and the list is that size of an array once created is fixed, but this is not case for 
# list. But we can change the shape of an array  by using reshape() method.

In [20]:
b=g.reshape(2,10)# this through an error because number of elements should be same.
b

ValueError: cannot reshape array of size 14 into shape (2,10)

In [21]:
b=g.reshape(2,7)
b

array([[ 1,  3,  5,  7,  9, 11, 13],
       [15, 17, 19, 21, 23, 25, 27]])

In [23]:
#now if you do not know the no of elemts in each row you can provide -1, numpy will determine the elements through axis.
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
x=a.reshape(5,-1)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
y=a.reshape(-1,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
y.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
x.ravel()#instead of y.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
#ocassionally it is required to convert the 1D array to 2d array with one column or by one row.
#1.by using reshape() 2. using newaxis with slicing
d=np.arange(5)

In [33]:
d.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [37]:
d[:,np.newaxis]#instead of d.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [39]:
d[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

## Universal function

In [41]:
# some binary universal function are:
#np.subtract
a=np.arange(1000)
a=np.subtract(a,1)

In [42]:
a

array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 17

In [43]:
# simmilary:np.add() for +
# np.multiply for *
# np.floor_divide for //
# np.mod for %

In [44]:
#some uniary functions
#np.sum()
#np.prod()
#np.mean()
#np.std()
#np.sqrt()
#np.log()
#np.var()
#np.min
#np.max

## Broadcasting

In [45]:
#It is a set of rule that instructs Numpy how to treat arrays of different shapes and dimension during arithmetic operation.

In [46]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [47]:
b=a+2
b

array([2, 3, 4, 5, 6, 7])

# the rules of boradcasting
## If two arrays are different dimensions dimension ones are added to the left of the shape of the array with fewer dimension to make them same

## once dimesion are equal , the size of arrays in each dimesion must be equal or 1 in atleast one of them otherwise it raised an
# error
## If an error is not raised ,then the size of the output array in each dimension  is the maximum of array size in that dimension.

In [56]:
a=np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
b=np.random.randint(1,10,4)
b

array([3, 7, 8, 6], dtype=int32)

In [58]:
b.shape

(4,)

In [59]:
print(a+b)

[[4. 8. 9. 7.]
 [4. 8. 9. 7.]]


• By Rule 1, a single 1 is added to the left of b shape to make b a two-dimensional
array as a; that is, we can think of b now as having shape (1, 4).
• The shape of a is (2, 4) and the shape of b is (1, 4). Therefore, Rule 2 does not
raise an error because the sizes in each dimension are either equal (here 4) or at
least one of them is 1 (for example, 2 in a and 1 in b).
• Rule 3 indicates that the size of the output is (max{2,1}, max{4,4}) so it is (2,
4). This means that array b is streched along its axis 0 (the left element in a
shape tuple) to match the size of a in that dimension.

In [62]:
a=np.arange(8).reshape(2,4,1)
print(a)
a.shape

[[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]


(2, 4, 1)

In [66]:
b=np.arange(4)
b.shape

(4,)

In [67]:
print(a+b)

[[[ 0  1  2  3]
  [ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]]

 [[ 4  5  6  7]
  [ 5  6  7  8]
  [ 6  7  8  9]
  [ 7  8  9 10]]]


• By Rule 1, a 1 is added to the left of b shape to make it a 3-dimensional array
as a; that is, we can think of b now as having shape (1, 1, 4).
• The shape of a is (2, 4, 1) and the shape of b is (1, 1, 4). Therefore, Rule 2 does
not raise an error because the sizes in each dimension are either equal or at least
one of them is 1.
• Rule 3 indicates that the size of the output is (max{2,1}, max{4,1}, max{1,4})
so it is (2, 4, 4). This means that array a is streched along its axis 2 (the third
element in its shape tuple) to make its size 4 (similar to b in that dimension), array
b is streched along its axis 1 to make its size 4 (similar to a in that dimension),
and finally array b is stretched along its axis 0 to make its size 2

In [72]:
m=np.arange(8).reshape(2,2,2)
print(m)
m.shape

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


(2, 2, 2)

In [73]:
b=np.arange(4)
b.shape


(4,)

In [74]:
print(m+b)

ValueError: operands could not be broadcast together with shapes (2,2,2) (4,) 